package br.com.mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Celular generated by hbm2java
 */
@Entity
@Table(name = "celular"
        , catalog = "mamore"
)
public class Celular implements java.io.Serializable {


    private Integer id;
    private CelularParticular celularParticular;
    private CelularCorporativo celularCorporativo;
    private Set<AssociacaoChipCelular> associacaoChipCelulars = new HashSet<AssociacaoChipCelular>(0);

    public Celular() {
    }

    public Celular(CelularParticular celularParticular, CelularCorporativo celularCorporativo, Set<AssociacaoChipCelular> associacaoChipCelulars) {
        this.celularParticular = celularParticular;
        this.celularCorporativo = celularCorporativo;
        this.associacaoChipCelulars = associacaoChipCelulars;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "celular")
    public CelularParticular getCelularParticular() {
        return this.celularParticular;
    }

    public void setCelularParticular(CelularParticular celularParticular) {
        this.celularParticular = celularParticular;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "celular")
    public CelularCorporativo getCelularCorporativo() {
        return this.celularCorporativo;
    }

    public void setCelularCorporativo(CelularCorporativo celularCorporativo) {
        this.celularCorporativo = celularCorporativo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "celular")
    public Set<AssociacaoChipCelular> getAssociacaoChipCelulars() {
        return this.associacaoChipCelulars;
    }

    public void setAssociacaoChipCelulars(Set<AssociacaoChipCelular> associacaoChipCelulars) {
        this.associacaoChipCelulars = associacaoChipCelulars;
    }


}


