package br.com.mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CelularParticular generated by hbm2java
 */
@Entity
@Table(name = "celular_particular"
        , catalog = "mamore"
)
public class CelularParticular implements java.io.Serializable {


    private Integer id;
    private Celular celular;

    public CelularParticular() {
    }

    public CelularParticular(Celular celular) {
        this.celular = celular;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "celular"))
    @Id
    @GeneratedValue(generator = "generator")


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Celular getCelular() {
        return this.celular;
    }

    public void setCelular(Celular celular) {
        this.celular = celular;
    }


}


