package br.com.mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Comissionado generated by hbm2java
 */
@Entity
@Table(name = "comissionado"
        , catalog = "mamore"
)
public class Comissionado implements java.io.Serializable {


    private Integer id;
    private CargoComissionado cargoComissionado;
    private Servidor servidor;

    public Comissionado() {
    }

    public Comissionado(CargoComissionado cargoComissionado, Servidor servidor) {
        this.cargoComissionado = cargoComissionado;
        this.servidor = servidor;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "servidor"))
    @Id
    @GeneratedValue(generator = "generator")


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cargo_comissionado_id", nullable = false)
    public CargoComissionado getCargoComissionado() {
        return this.cargoComissionado;
    }

    public void setCargoComissionado(CargoComissionado cargoComissionado) {
        this.cargoComissionado = cargoComissionado;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Servidor getServidor() {
        return this.servidor;
    }

    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }


}


