package br.com.mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Disponibilizacao generated by hbm2java
 */
@Entity
@Table(name = "disponibilizacao"
        , catalog = "mamore"
)
public class Disponibilizacao implements java.io.Serializable {


    private Integer id;
    private Linha linha;
    private Servidor servidor;
    private Date dataDisponibilizacao;

    public Disponibilizacao() {
    }

    public Disponibilizacao(Linha linha, Servidor servidor, Date dataDisponibilizacao) {
        this.linha = linha;
        this.servidor = servidor;
        this.dataDisponibilizacao = dataDisponibilizacao;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "linha_id", nullable = false)
    public Linha getLinha() {
        return this.linha;
    }

    public void setLinha(Linha linha) {
        this.linha = linha;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "servidor_id", nullable = false)
    public Servidor getServidor() {
        return this.servidor;
    }

    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_disponibilizacao", nullable = false, length = 10)
    public Date getDataDisponibilizacao() {
        return this.dataDisponibilizacao;
    }

    public void setDataDisponibilizacao(Date dataDisponibilizacao) {
        this.dataDisponibilizacao = dataDisponibilizacao;
    }


}


