package br.com.mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fabricante generated by hbm2java
 */
@Entity
@Table(name = "fabricante"
        , catalog = "mamore"
)
public class Fabricante implements java.io.Serializable {


    private Integer id;
    private String nome;
    private Set<CelularCorporativo> celularCorporativos = new HashSet<CelularCorporativo>(0);

    public Fabricante() {
    }

    public Fabricante(String nome, Set<CelularCorporativo> celularCorporativos) {
        this.nome = nome;
        this.celularCorporativos = celularCorporativos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "nome", length = 10)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fabricante")
    public Set<CelularCorporativo> getCelularCorporativos() {
        return this.celularCorporativos;
    }

    public void setCelularCorporativos(Set<CelularCorporativo> celularCorporativos) {
        this.celularCorporativos = celularCorporativos;
    }


}


