package br.com.mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teste generated by hbm2java
 */
@Entity
@Table(name = "teste"
        , catalog = "mamore"
)
public class Teste implements java.io.Serializable {


    private String nome;

    public Teste() {
    }

    public Teste(String nome) {
        this.nome = nome;
    }

    @Id


    @Column(name = "nome", length = 30)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }


}


