package mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AssociacaoLinhaChip generated by hbm2java
 */
@Entity
@Table(name="associacao_linha_chip"
    ,catalog="mamore"
)
public class AssociacaoLinhaChip  implements java.io.Serializable {


     private Integer id;
     private Chip chip;
     private Linha linha;

    public AssociacaoLinhaChip() {
    }

    public AssociacaoLinhaChip(Chip chip, Linha linha) {
       this.chip = chip;
       this.linha = linha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chip_id", nullable=false)
    public Chip getChip() {
        return this.chip;
    }
    
    public void setChip(Chip chip) {
        this.chip = chip;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="linha_id", nullable=false)
    public Linha getLinha() {
        return this.linha;
    }
    
    public void setLinha(Linha linha) {
        this.linha = linha;
    }




}


