package mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CargoComissionado generated by hbm2java
 */
@Entity
@Table(name="cargo_comissionado"
    ,catalog="mamore"
)
public class CargoComissionado  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private Set<Comissionado> comissionados = new HashSet<Comissionado>(0);
     private Set<Desempenho> desempenhos = new HashSet<Desempenho>(0);

    public CargoComissionado() {
    }

	
    public CargoComissionado(String descricao) {
        this.descricao = descricao;
    }
    public CargoComissionado(String descricao, Set<Comissionado> comissionados, Set<Desempenho> desempenhos) {
       this.descricao = descricao;
       this.comissionados = comissionados;
       this.desempenhos = desempenhos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descricao", nullable=false, length=30)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargoComissionado")
    public Set<Comissionado> getComissionados() {
        return this.comissionados;
    }
    
    public void setComissionados(Set<Comissionado> comissionados) {
        this.comissionados = comissionados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargoComissionado")
    public Set<Desempenho> getDesempenhos() {
        return this.desempenhos;
    }
    
    public void setDesempenhos(Set<Desempenho> desempenhos) {
        this.desempenhos = desempenhos;
    }




}


