package mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Desempenho generated by hbm2java
 */
@Entity
@Table(name="desempenho"
    ,catalog="mamore"
)
public class Desempenho  implements java.io.Serializable {


     private Integer id;
     private CargoComissionado cargoComissionado;
     private Efetivo efetivo;
     private Funcao funcao;

    public Desempenho() {
    }

    public Desempenho(CargoComissionado cargoComissionado, Efetivo efetivo, Funcao funcao) {
       this.cargoComissionado = cargoComissionado;
       this.efetivo = efetivo;
       this.funcao = funcao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cargo_comissionado_id", nullable=false)
    public CargoComissionado getCargoComissionado() {
        return this.cargoComissionado;
    }
    
    public void setCargoComissionado(CargoComissionado cargoComissionado) {
        this.cargoComissionado = cargoComissionado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="efetivo_id", nullable=false)
    public Efetivo getEfetivo() {
        return this.efetivo;
    }
    
    public void setEfetivo(Efetivo efetivo) {
        this.efetivo = efetivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcao_id", nullable=false)
    public Funcao getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
    }




}


