package mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Efetivo generated by hbm2java
 */
@Entity
@Table(name="efetivo"
    ,catalog="mamore"
)
public class Efetivo  implements java.io.Serializable {


     private Integer id;
     private CargoEfetivo cargoEfetivo;
     private Servidor servidor;
     private Set<Desempenho> desempenhos = new HashSet<Desempenho>(0);

    public Efetivo() {
    }

	
    public Efetivo(CargoEfetivo cargoEfetivo, Servidor servidor) {
        this.cargoEfetivo = cargoEfetivo;
        this.servidor = servidor;
    }
    public Efetivo(CargoEfetivo cargoEfetivo, Servidor servidor, Set<Desempenho> desempenhos) {
       this.cargoEfetivo = cargoEfetivo;
       this.servidor = servidor;
       this.desempenhos = desempenhos;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="servidor"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cargo_efetivo_id", nullable=false)
    public CargoEfetivo getCargoEfetivo() {
        return this.cargoEfetivo;
    }
    
    public void setCargoEfetivo(CargoEfetivo cargoEfetivo) {
        this.cargoEfetivo = cargoEfetivo;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="efetivo")
    public Set<Desempenho> getDesempenhos() {
        return this.desempenhos;
    }
    
    public void setDesempenhos(Set<Desempenho> desempenhos) {
        this.desempenhos = desempenhos;
    }




}


