package mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,catalog="mamore"
)
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private Set<Terceirizado> terceirizados = new HashSet<Terceirizado>(0);

    public Empresa() {
    }

	
    public Empresa(String descricao) {
        this.descricao = descricao;
    }
    public Empresa(String descricao, Set<Terceirizado> terceirizados) {
       this.descricao = descricao;
       this.terceirizados = terceirizados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descricao", nullable=false, length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Terceirizado> getTerceirizados() {
        return this.terceirizados;
    }
    
    public void setTerceirizados(Set<Terceirizado> terceirizados) {
        this.terceirizados = terceirizados;
    }




}


