package mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name="modelo"
    ,catalog="mamore"
)
public class Modelo  implements java.io.Serializable {


     private Integer id;
     private String descricaoModelo;
     private Set<CelularCorporativo> celularCorporativos = new HashSet<CelularCorporativo>(0);

    public Modelo() {
    }

    public Modelo(String descricaoModelo, Set<CelularCorporativo> celularCorporativos) {
       this.descricaoModelo = descricaoModelo;
       this.celularCorporativos = celularCorporativos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descricao_modelo", length=30)
    public String getDescricaoModelo() {
        return this.descricaoModelo;
    }
    
    public void setDescricaoModelo(String descricaoModelo) {
        this.descricaoModelo = descricaoModelo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="modelo")
    public Set<CelularCorporativo> getCelularCorporativos() {
        return this.celularCorporativos;
    }
    
    public void setCelularCorporativos(Set<CelularCorporativo> celularCorporativos) {
        this.celularCorporativos = celularCorporativos;
    }




}


