package mm.model;
// Generated 31/07/2017 19:00:58 by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Servidor generated by hbm2java
 */
@Entity
@Table(name="servidor"
    ,catalog="mamore"
)
public class Servidor  implements java.io.Serializable {


     private Integer id;
     private Unidade unidade;
     private String matricula;
     private String cpf;
     private String nome;
     private Efetivo efetivo;
     private Set<Disponibilizacao> disponibilizacaos = new HashSet<Disponibilizacao>(0);
     private Comissionado comissionado;
     private Terceirizado terceirizado;

    public Servidor() {
    }

	
    public Servidor(Unidade unidade, String matricula, String cpf, String nome) {
        this.unidade = unidade;
        this.matricula = matricula;
        this.cpf = cpf;
        this.nome = nome;
    }
    public Servidor(Unidade unidade, String matricula, String cpf, String nome, Efetivo efetivo, Set<Disponibilizacao> disponibilizacaos, Comissionado comissionado, Terceirizado terceirizado) {
       this.unidade = unidade;
       this.matricula = matricula;
       this.cpf = cpf;
       this.nome = nome;
       this.efetivo = efetivo;
       this.disponibilizacaos = disponibilizacaos;
       this.comissionado = comissionado;
       this.terceirizado = terceirizado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unidade_id", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

    
    @Column(name="matricula", nullable=false, length=11)
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    
    @Column(name="cpf", nullable=false, length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="nome", nullable=false, length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="servidor")
    public Efetivo getEfetivo() {
        return this.efetivo;
    }
    
    public void setEfetivo(Efetivo efetivo) {
        this.efetivo = efetivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servidor")
    public Set<Disponibilizacao> getDisponibilizacaos() {
        return this.disponibilizacaos;
    }
    
    public void setDisponibilizacaos(Set<Disponibilizacao> disponibilizacaos) {
        this.disponibilizacaos = disponibilizacaos;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="servidor")
    public Comissionado getComissionado() {
        return this.comissionado;
    }
    
    public void setComissionado(Comissionado comissionado) {
        this.comissionado = comissionado;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="servidor")
    public Terceirizado getTerceirizado() {
        return this.terceirizado;
    }
    
    public void setTerceirizado(Terceirizado terceirizado) {
        this.terceirizado = terceirizado;
    }




}


